/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.82
 * Generated at: 2024-02-06 03:09:12 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.board;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class faq_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/resources/css/notice/notice.css\">\r\n");
      out.write("<script\r\n");
      out.write("  src=\"https://code.jquery.com/jquery-3.4.1.js\"\r\n");
      out.write("  integrity=\"sha256-WpOohJOqMqqyKL9FccASB9O0KwACQJpFTUBLTYOVvVU=\"\r\n");
      out.write("  crossorigin=\"anonymous\"></script>\r\n");
      out.write("</head>\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/views/include/header.jsp", out, false);
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("<div id=\"faq\">\r\n");
      out.write("  <h2>FAQ</h2>\r\n");
      out.write("<ol class=\"qna-list accordion\">\r\n");
      out.write("						<li class=\"qna-item\">\r\n");
      out.write("							<div class=\"question-article\">\r\n");
      out.write("								<a href=\"#!\" class=\"question btn-fold\">\r\n");
      out.write("									<strong class=\"blind\">질문:</strong>\r\n");
      out.write("									<span class=\"q\">Q</span>방문 상담이 가능한가요?\r\n");
      out.write("								</a>\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"answer-article\">\r\n");
      out.write("								<strong class=\"blind\">답변</strong>\r\n");
      out.write("								<div id=\"answer-cnt\">\r\n");
      out.write("									<p>보도자료 배포 결과는 뉴스 가치, 주제, 배포시기 등에 따라 달라집니다. </p>\r\n");
      out.write("									<p>평균적으로 <a href=\"#!\">스탠다드 서비스</a>는 보도자료 한 건당 7.9개 기사가 보도되며, 프리미엄 서비스는 평균 17개 기사가 보도됩니다.</p>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("						</li>\r\n");
      out.write("						<li class=\"qna-item\">\r\n");
      out.write("							<div class=\"question-article\">\r\n");
      out.write("								<a href=\"#!\" class=\"question btn-fold\">\r\n");
      out.write("									<strong class=\"blind\">질문:</strong>\r\n");
      out.write("									<span class=\"q\">Q</span>승인된 보도자료를 수정 또는 삭제하려면 어떻게 해야 하나요?\r\n");
      out.write("								</a>\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"answer-article\">\r\n");
      out.write("								<strong class=\"blind\">답변</strong>\r\n");
      out.write("								<div id=\"answer-cnt\">\r\n");
      out.write("									<p>보도자료 배포 결과는 뉴스 가치, 주제, 배포시기 등에 따라 달라집니다. </p>\r\n");
      out.write("									<p>평균적으로 <a href=\"#!\">스탠다드 서비스</a>는 보도자료 한 건당 7.9개 기사가 보도되며, 프리미엄 서비스는 평균 17개 기사가 보도됩니다.</p>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("						</li>\r\n");
      out.write("						<li class=\"qna-item\">\r\n");
      out.write("							<div class=\"question-article\">\r\n");
      out.write("								<a href=\"#!\" class=\"question btn-fold\">\r\n");
      out.write("									<strong class=\"blind\">질문:</strong>\r\n");
      out.write("									<span class=\"q\">Q</span>방문 상담이 가능한가요?\r\n");
      out.write("								</a>\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"answer-article\">\r\n");
      out.write("								<strong class=\"blind\">답변</strong>\r\n");
      out.write("								<div id=\"answer-cnt\">\r\n");
      out.write("									<p>보도자료 배포 결과는 뉴스 가치, 주제, 배포시기 등에 따라 달라집니다. </p>\r\n");
      out.write("									<p>평균적으로 <a href=\"#!\">스탠다드 서비스</a>는 보도자료 한 건당 7.9개 기사가 보도되며, 프리미엄 서비스는 평균 17개 기사가 보도됩니다.</p>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("						</li>\r\n");
      out.write("						<li class=\"qna-item\">\r\n");
      out.write("							<div class=\"question-article\">\r\n");
      out.write("								<a href=\"#!\" class=\"question btn-fold\">\r\n");
      out.write("									<strong class=\"blind\">질문:</strong>\r\n");
      out.write("									<span class=\"q\">Q</span>방문 상담이 가능한가요?\r\n");
      out.write("								</a>\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"answer-article\">\r\n");
      out.write("								<strong class=\"blind\">답변</strong>\r\n");
      out.write("								<div id=\"answer-cnt\">\r\n");
      out.write("									<p>보도자료 배포 결과는 뉴스 가치, 주제, 배포시기 등에 따라 달라집니다. </p>\r\n");
      out.write("									<p>평균적으로 <a href=\"#!\">스탠다드 서비스</a>는 보도자료 한 건당 7.9개 기사가 보도되며, 프리미엄 서비스는 평균 17개 기사가 보도됩니다.</p>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("						</li>\r\n");
      out.write("						<li class=\"qna-item\">\r\n");
      out.write("							<div class=\"question-article\">\r\n");
      out.write("								<a href=\"#!\" class=\"question btn-fold\">\r\n");
      out.write("									<strong class=\"blind\">질문:</strong>\r\n");
      out.write("									<span class=\"q\">Q</span>방문 상담이 가능한가요?\r\n");
      out.write("								</a>\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"answer-article\">\r\n");
      out.write("								<strong class=\"blind\">답변</strong>\r\n");
      out.write("								<div id=\"answer-cnt\">\r\n");
      out.write("									<p>보도자료 배포 결과는 뉴스 가치, 주제, 배포시기 등에 따라 달라집니다. </p>\r\n");
      out.write("									<p>평균적으로 <a href=\"#!\">스탠다드 서비스</a>는 보도자료 한 건당 7.9개 기사가 보도되며, 프리미엄 서비스는 평균 17개 기사가 보도됩니다.</p>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("						</li>\r\n");
      out.write("						<li class=\"qna-item\">\r\n");
      out.write("							<div class=\"question-article\">\r\n");
      out.write("								<a href=\"#!\" class=\"question btn-fold\">\r\n");
      out.write("									<strong class=\"blind\">질문:</strong>\r\n");
      out.write("									<span class=\"q\">Q</span>방문 상담이 가능한가요?\r\n");
      out.write("								</a>\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"answer-article\">\r\n");
      out.write("								<strong class=\"blind\">답변</strong>\r\n");
      out.write("								<div id=\"answer-cnt\">\r\n");
      out.write("									<p>보도자료 배포 결과는 뉴스 가치, 주제, 배포시기 등에 따라 달라집니다. </p>\r\n");
      out.write("									<p>평균적으로 <a href=\"#!\">스탠다드 서비스</a>는 보도자료 한 건당 7.9개 기사가 보도되며, 프리미엄 서비스는 평균 17개 기사가 보도됩니다.</p>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("						</li>\r\n");
      out.write("						<li class=\"qna-item\">\r\n");
      out.write("							<div class=\"question-article\">\r\n");
      out.write("								<a href=\"#!\" class=\"question btn-fold\">\r\n");
      out.write("									<strong class=\"blind\">질문:</strong>\r\n");
      out.write("									<span class=\"q\">Q</span>방문 상담이 가능한가요?\r\n");
      out.write("								</a>\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"answer-article\">\r\n");
      out.write("								<strong class=\"blind\">답변</strong>\r\n");
      out.write("								<div id=\"answer-cnt\">\r\n");
      out.write("									<p>보도자료 배포 결과는 뉴스 가치, 주제, 배포시기 등에 따라 달라집니다. </p>\r\n");
      out.write("									<p>평균적으로 <a href=\"#!\">스탠다드 서비스</a>는 보도자료 한 건당 7.9개 기사가 보도되며, 프리미엄 서비스는 평균 17개 기사가 보도됩니다.</p>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("						</li>\r\n");
      out.write("					</ol>\r\n");
      out.write("  </div>\r\n");
      out.write("</body>\r\n");
      out.write("<script>\r\n");
      out.write("$(function() {\r\n");
      out.write("	$('.btn-fold').on('click', function(){\r\n");
      out.write("		if(!$(this).closest('.qna-item').hasClass('on')){\r\n");
      out.write("			$('.qna-item').removeClass('on').find('.answer-article').hide();\r\n");
      out.write("			 var oft = $(this).offset().top;\r\n");
      out.write("			$('html,body').stop().animate({scrollTop:oft - 250 }, 300)\r\n");
      out.write("			$(this).closest('.qna-item').addClass('on').find('.answer-article').slideDown(300)\r\n");
      out.write("\r\n");
      out.write("		}else{\r\n");
      out.write("			$(this).closest('.qna-item').removeClass('on').find('.answer-article').slideUp(300)\r\n");
      out.write("		}\r\n");
      out.write("	})\r\n");
      out.write("});\r\n");
      out.write("</script>\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/views/include/footer.jsp", out, false);
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
